name: kmeans2
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7.4
  - pytorch=1.3.0
  - torchvision=0.4.1
  - numpy
  - scikit-learn
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - tqdm
